# Generated by Django 4.2.7 on 2025-08-08 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_ethiopia_address_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='lot_size',
        ),
        migrations.RemoveField(
            model_name='property',
            name='price_per_sqft',
        ),
        migrations.RemoveField(
            model_name='property',
            name='square_feet',
        ),
        migrations.RemoveField(
            model_name='property',
            name='state',
        ),
        migrations.RemoveField(
            model_name='property',
            name='zip_code',
        ),
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.CharField(help_text='Full address', max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(help_text='City (e.g., Addis Ababa)', max_length=100),
        ),
    ]
