# Generated by Django 4.2.7 on 2025-08-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_remove_property_lot_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
